### PR TITLE
static builds and packaging for kovri

### PR DESCRIPTION
**Pull request by danrmiller**
add schedulers for kovri static builds and installer packaging.

### CODE REVIEW

**Comment by danrmiller** [comment]
Oh, this is for #35

**Comment by danrmiller** [comment]
@luigi1111 this one is ready.

**Comment by luigi1111** [comment]
I may have fallen behind. There appears to be a conflict here. Please advise.

**Comment by danrmiller** [comment]
Sorry @luigi1111, now I fell behind. Let's try it now.

**Comment by luigi1111** [comment]
Thanks.

**Pull request merged**
