### PR TITLE
Buildbot: update config for kovri installers

### PR DESCRIPTION
**Pull request by anonimal**

### CODE REVIEW

**Comment by anonimal** [comment]
Closes #92. Referencing #88.

**Comment by danrmiller** [comment]
These changes are now active on buildbot.

**Comment by anonimal** [comment]
Thank you @danrmiller 👍

**Comment by danrmiller** [comment]
+resolved

**Comment by anonimal** [comment]
@danrmiller why close before merging?

**Comment by danrmiller** [comment]
I intended for it to merge and close, as I had tested that in a test repo.

-resolved

**Comment by fluffypony** [comment]
I'm confused - must this be merged or not? lol

**Pull request merged**
